package BufferApp;


/**
* BufferApp/Buffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* dimanche 28 avril 2024 16 h 36 CEST
*/

public interface Buffer extends BufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Buffer
